### ISSUE TITLE
Error Handling on Signup Page

### ISSUE THREAD

**Issue by peymanmortazavi** [QuantifiedSelfless/quantifiedSelf#64]
Regardless of backend's respond, in front-end the wait message shows up instead of displaying the error.

**Comment by wannabeCitizen** [comment]
Fixing this now. It will display the error however the dialogue wait message will show up automatically. I have to do it this way since we want that to happen immediately upon click and we don't know whether there will be an error or not until the call goes through.

I just pushed this up to my repo; however, I can't test it because right now everything is broken due to that import error

**Comment by wannabeCitizen** [comment]
Working now!
